# Project information
site_name: wolproxypycli
site_url: https://github.com/bateman/wolproxypycli
site_description: A PyPI module and Typer (CLI) app for sending Wake-On-LAN packets.
site_author: Fabio Calefato <fabio.calefato@uniba.it>

# Repository
repo_url: https://github.com/bateman/wolproxypycli
repo_name: bateman/wolproxypycli
edit_uri: "" #disables edit button

# Copyright
copyright: MIT License 2021-2024, Fabio Calefato

# Configuration
theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [wolproxypycli]

nav:
  - Home: index.md
  - About: about.md
  - Docstrings:
    - CLI module: cli.md
