name: pypi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, test, and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: Gr1N/setup-poetry@v8
    - run: poetry --version
    - name: Install dependencies
      run: make install
    #- name: Run tests
    #  run: make test
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.17
      with:
        python_version: 3.12
        pypi_token: ${{ secrets.PYPI_TOKEN }}
