name: pypi

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build, test, and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: Gr1N/setup-poetry@v8
    - run: poetry --version
    - name: Install dependencies
      run: make install
    #- name: Run tests
    #  run: make test
    - name: Publish PyPi package
      uses: celsiusnarhwal/poetry-publish@v2
      with:
        python-version: 3.12
        poetry-version: 1.7.1
        token: ${{ secrets.PYPI_TOKEN }}
